-- Custom migration: triggers, RLS, seed data, tsvector
-- This file is hand-written (not generated by drizzle-kit)

-- 1. Enable pgcrypto extension (may already exist from init-db.sql)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. State transition trigger
CREATE OR REPLACE FUNCTION validate_task_transition()
RETURNS TRIGGER AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM task_valid_transitions
    WHERE from_state = OLD.state AND to_state = NEW.state
  ) THEN
    RAISE EXCEPTION 'Invalid task state transition from % to %', OLD.state, NEW.state;
  END IF;
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER task_state_transition_check
  BEFORE UPDATE ON tasks
  FOR EACH ROW
  WHEN (OLD.state IS DISTINCT FROM NEW.state)
  EXECUTE FUNCTION validate_task_transition();

-- 3. Audit table RLS
ALTER TABLE audit_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_entries FORCE ROW LEVEL SECURITY;

CREATE POLICY audit_no_update ON audit_entries
  AS RESTRICTIVE FOR UPDATE USING (false);
CREATE POLICY audit_no_delete ON audit_entries
  AS RESTRICTIVE FOR DELETE USING (false);
CREATE POLICY audit_allow_insert ON audit_entries
  FOR INSERT WITH CHECK (true);
CREATE POLICY audit_allow_select ON audit_entries
  FOR SELECT USING (true);

-- 4. Seed valid transitions (22 explicit + 13 cancelled = 35 total)
INSERT INTO task_valid_transitions (from_state, to_state) VALUES
  ('created', 'needs_clarification'), ('created', 'assigned'),
  ('needs_clarification', 'assigned'),
  ('assigned', 'in_progress'),
  ('in_progress', 'evidence_ready'), ('in_progress', 'failed'), ('in_progress', 'paused'),
  ('paused', 'in_progress'), ('paused', 'cancelled'),
  ('evidence_ready', 'changes_requested'), ('evidence_ready', 'approved'),
  ('changes_requested', 'in_progress'),
  ('approved', 'pr_created'),
  ('pr_created', 'external_checks_pending'),
  ('external_checks_pending', 'addressing_review_feedback'),
  ('external_checks_pending', 'external_blocked'),
  ('external_checks_pending', 'merge_ready'),
  ('addressing_review_feedback', 'external_checks_pending'),
  ('external_blocked', 'external_checks_pending'),
  ('merge_ready', 'merged'), ('merge_ready', 'failed');

-- Cancelled from all non-terminal states
INSERT INTO task_valid_transitions (from_state, to_state)
SELECT s.state, 'cancelled'::task_state
FROM unnest(ARRAY[
  'created','needs_clarification','assigned','in_progress','paused',
  'evidence_ready','changes_requested','approved','pr_created',
  'external_checks_pending','addressing_review_feedback','external_blocked','merge_ready'
]::task_state[]) AS s(state)
ON CONFLICT DO NOTHING;

-- 5. tsvector generated column on code_symbols (Drizzle Kit can't generate this)
ALTER TABLE code_symbols ADD COLUMN search_vector tsvector
  GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(symbol_name, '') || ' ' || coalesce(file_path, ''))
  ) STORED;
CREATE INDEX code_symbols_search_vector_idx ON code_symbols USING gin (search_vector);

-- 6. Grant permissions to factory_app role
GRANT USAGE ON SCHEMA public TO factory_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO factory_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO factory_app;

-- Grant permissions to factory_admin role (can bypass RLS)
GRANT ALL ON SCHEMA public TO factory_admin;
GRANT ALL ON ALL TABLES IN SCHEMA public TO factory_admin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO factory_admin;
